//GET Miningservers
export const LOAD_MININSERVERS = 'LOAD_MININSERVERS'
// GET Faqs
export const GET_FAQS = 'GET_FAQS'
// CREATE New Faq
export const CREATE_NEW_FAQ = 'CREATE_NEW_FAQ'
export const CREATE_NEW_FAQ_SUCCESS = 'CREATE_NEW_FAQ_SUCCESS'
export const CREATE_NEW_FAQ_FAILED = 'CREATE_NEW_FAQ_FAILED'
export const SET_CREATESUCCESS_DEFAULT = 'SET_CREATESUCCESS_DEFAULT'

//UPDATE a Faq
export const UPDATE_FAQ_SUCCESS = 'UPDATE_FAQ_SUCCESS'
export const SET_UPDATESUCCESS_DEFAULT = 'SET_UPDATESUCCESS_DEFAULT'